//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePedido
    {
        public int idDetallePedido { get; set; }
        public string Observaciones { get; set; }
        public int idPlato { get; set; }
        public int idPedido { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Plato Plato { get; set; }
    }
}
