//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MesaxPedido
    {
        public int Capacidad { get; set; }
        public string Estado { get; set; }
        public int idPedido { get; set; }
        public int IdMesa { get; set; }
    
        public virtual Mesa Mesa { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}
